[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  frameworkd = "#custom"
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "dist"
  autoLaunch = false